"""
Plain-script (no pytest) checks of the static_rom package, in the style of
phase1/test_eval_protocol.py. Synthetic fixtures only, plus the checked-in
pimpleFoam_v2006/icoFoam graph fixtures already used by
validation/check_pimplefoam_graph.py -- never touches the real dataset.

Run with: python -m static_rom.test_static_rom  (from phase2/)
"""

from __future__ import annotations

import math
import os
import tempfile

import torch as pt

from extractor.operator_graph import build_operator_graph, equation_terms
from static_rom.case_activity import read_case_activity
from static_rom.opinf import (
    build_regressors, build_target, fit_ridge, make_basis_ctx, pod_basis, project, reconstruct,
    rollout, select_lambda,
)
from static_rom.term_library import Library, arm2_library, arm3_library, register_extra_family

pt.set_default_dtype(pt.float64)

UEQN = "fixtures/pimpleFoam_v2006/UEqn.H"
PEQN = "fixtures/pimpleFoam_v2006/pEqn.H"
FVSCHEMES = "fixtures/pimpleFoam_v2006/fvSchemes_of_cylinder2D"
TURB_PROPS = "fixtures/pimpleFoam_v2006/turbulenceProperties_of_cylinder2D"
ICOFOAM_UNKNOWN = "fixtures/icoFoam_modified_unknown.C"
ICOFOAM_SCHEMES = "fixtures/fvSchemes"
DATASET_CASE = "../data/datasets_29_10_2021/datasets/of_cylinder2D_binary"

UEQN_DRAG = "fixtures/pimpleFoam_v2006_drag/UEqn.H"
PEQN_DRAG = "fixtures/pimpleFoam_v2006_drag/pEqn.H"
FVSCHEMES_DRAG = "fixtures/pimpleFoam_v2006_drag/fvSchemes_of_cylinder2D"
TURB_PROPS_DRAG = "fixtures/pimpleFoam_v2006_drag/turbulenceProperties_of_cylinder2D"


def check(name: str, condition: bool, detail: str = "") -> None:
    status = "PASS" if condition else "FAIL"
    print(f"[{status}] {name}" + (f"  ({detail})" if detail else ""))
    assert condition, f"{name} failed: {detail}"


def _build_pimplefoam_graph():
    return build_operator_graph(
        UEQN, fvschemes_path=FVSCHEMES, extra_sources=[PEQN],
        include_unqualified=True, expand_dispatch=True,
        turbulence_properties_path=TURB_PROPS,
    )


def _make_quadratic_system_data(n_steps: int, dt: float) -> tuple[pt.Tensor, pt.Tensor, pt.Tensor, pt.Tensor]:
    """A hand-specified 2D quadratic discrete system z_{k+1} = c + A z_k +
    H (z_k (x) z_k)_unique, generated by explicit deterministic formulas
    (no RNG, per project convention). Returns (Z, c, A, H)."""
    c = pt.tensor([0.05, -0.02], dtype=pt.float64)
    A = pt.tensor([[0.9, 0.05], [-0.03, 0.85]], dtype=pt.float64)
    H = pt.tensor([[0.01, -0.02, 0.015], [0.005, 0.01, -0.01]], dtype=pt.float64)  # cols: z1^2, z1z2, z2^2

    def step(z):
        quad = pt.tensor([z[0] * z[0], z[0] * z[1], z[1] * z[1]], dtype=pt.float64)
        return c + A @ z + H @ quad

    z = pt.tensor([1.0, -0.5], dtype=pt.float64)
    traj = [z]
    for _ in range(n_steps):
        z = step(z)
        traj.append(z)
    Z = pt.stack(traj, dim=1)
    return Z, c, A, H


def check_quadratic_discrete_recovery() -> None:
    Z, c_true, A_true, H_true = _make_quadratic_system_data(n_steps=200, dt=0.01)
    library = Library(families=("const", "lin", "quad"), extras=())
    D, groups = build_regressors(Z[:, :-1], library)
    Y = Z[:, 1:]
    coef = fit_ridge(D, Y, 0.0, 0.0, groups)

    c_hat = coef[:, groups["const"]].squeeze(-1)
    A_hat = coef[:, groups["lin"]]
    H_hat = coef[:, groups["quad"]]

    check("quadratic discrete: c recovered", pt.allclose(c_hat, c_true, atol=1e-8),
          f"max|diff|={ (c_hat - c_true).abs().max().item():.2e}")
    check("quadratic discrete: A recovered", pt.allclose(A_hat, A_true, atol=1e-8),
          f"max|diff|={ (A_hat - A_true).abs().max().item():.2e}")
    check("quadratic discrete: H recovered", pt.allclose(H_hat, H_true, atol=1e-8),
          f"max|diff|={ (H_hat - H_true).abs().max().item():.2e}")


def check_quadratic_continuous_recovery() -> None:
    c_true = pt.tensor([0.05, -0.02], dtype=pt.float64)
    A_true = pt.tensor([[-0.8, 0.05], [-0.03, -0.85]], dtype=pt.float64)
    H_true = pt.tensor([[0.01, -0.02, 0.015], [0.005, 0.01, -0.01]], dtype=pt.float64)

    def f(z):
        quad = pt.tensor([z[0] * z[0], z[0] * z[1], z[1] * z[1]], dtype=pt.float64)
        return c_true + A_true @ z + H_true @ quad

    dt = 0.001
    z = pt.tensor([1.0, -0.5], dtype=pt.float64)
    traj = [z]
    for _ in range(400):
        k1 = f(z); k2 = f(z + 0.5 * dt * k1); k3 = f(z + 0.5 * dt * k2); k4 = f(z + dt * k3)
        z = z + (dt / 6.0) * (k1 + 2 * k2 + 2 * k3 + k4)
        traj.append(z)
    Z = pt.stack(traj, dim=1)

    library = Library(families=("const", "lin", "quad"), extras=())
    Z_input, Y, _time_index, trunc = build_target(Z, "continuous", dt)
    D, groups = build_regressors(Z_input, library)
    coef = fit_ridge(D, Y, 0.0, 0.0, groups)

    c_hat = coef[:, groups["const"]].squeeze(-1)
    A_hat = coef[:, groups["lin"]]
    H_hat = coef[:, groups["quad"]]

    check("quadratic continuous: c recovered", (c_hat - c_true).abs().max().item() < 1e-5,
          f"max|diff|={ (c_hat - c_true).abs().max().item():.2e}")
    check("quadratic continuous: A recovered", (A_hat - A_true).abs().max().item() < 1e-4,
          f"max|diff|={ (A_hat - A_true).abs().max().item():.2e}")
    check("quadratic continuous: H recovered", (H_hat - H_true).abs().max().item() < 1e-3,
          f"max|diff|={ (H_hat - H_true).abs().max().item():.2e}")
    check("quadratic continuous: truncation estimate is finite and small",
          math.isfinite(trunc) and trunc < 1.0, f"trunc={trunc:.2e}")


def check_linear_map_recovery() -> None:
    """A pure linear system (no quadratic/const term) recovered by a
    {lin}-only library, lambda=0, via the raw (uncentred) POD basis, in
    the spirit of DMD's exact-recovery-of-a-linear-operator property."""
    A = pt.tensor([
        [0.98, 0.10, 0.0, -0.02],
        [-0.10, 0.98, 0.02, 0.0],
        [0.01, 0.0, 0.95, 0.05],
        [0.0, 0.01, -0.05, 0.95],
    ], dtype=pt.float64)
    x = pt.tensor([1.0, 0.3, -0.4, 0.2], dtype=pt.float64)
    traj = [x]
    for _ in range(60):
        x = A @ x
        traj.append(x)
    X = pt.stack(traj, dim=1)

    basis = pod_basis(X, r=4, center=False)
    Z = project(basis, X)

    library = Library(families=("lin",), extras=())
    D, groups = build_regressors(Z[:, :-1], library)
    Y = Z[:, 1:]
    coef = fit_ridge(D, Y, 0.0, 0.0, groups)

    traj_pred, diverged, _ = rollout(coef, Z[:, 0], n_steps=X.shape[1] - 1, kind="discrete", library=library)
    X_pred = basis.modes @ traj_pred
    err = (pt.linalg.norm(X_pred - X) / pt.linalg.norm(X)).item()
    check("linear map recovery: not diverged", not diverged)
    check("linear map recovery: forecast matches true trajectory", err < 1e-8, f"err={err:.2e}")


def check_arm2_families() -> None:
    lib = arm2_library()
    check("arm2_library families == (const, lin, quad)", lib.families == ("const", "lin", "quad"),
          f"got {lib.families}")


def check_arm3_matches_arm2_on_dataset_case() -> None:
    g = _build_pimplefoam_graph()
    lib3 = arm3_library(g, equation="UEqn", case_dir=DATASET_CASE)
    lib2 = arm2_library()
    check("arm3_library(pimpleFoam, dataset case) families == arm2 families",
          lib3.families == lib2.families, f"arm3={lib3.families} arm2={lib2.families}")
    check("arm3_library provenance is non-empty", len(lib3.provenance) > 0,
          f"{len(lib3.provenance)} rows")


def check_arm3_raises_on_needs_review() -> None:
    g = build_operator_graph(ICOFOAM_UNKNOWN, ICOFOAM_SCHEMES, include_unqualified=True)
    raised = False
    try:
        arm3_library(g, equation="UEqn", case_dir=DATASET_CASE)
    except ValueError:
        raised = True
    check("arm3_library raises on a needs_review term (customForcing::spongeSink)", raised)


def check_arm3_raises_on_active_fvoptions() -> None:
    g = _build_pimplefoam_graph()
    with tempfile.TemporaryDirectory() as tmp:
        os.makedirs(os.path.join(tmp, "constant"))
        os.makedirs(os.path.join(tmp, "system"))
        with open(os.path.join(tmp, "constant", "transportProperties"), "w") as f:
            f.write("transportModel Newtonian;\nnu 1.0e-3;\n")
        with open(os.path.join(tmp, "constant", "turbulenceProperties"), "w") as f:
            f.write("simulationType laminar;\n")
        with open(os.path.join(tmp, "constant", "fvOptions"), "w") as f:
            f.write("momentumSource\n{\n    active true;\n    type meanVelocityForce;\n}\n")
        with open(os.path.join(tmp, "system", "fvSchemes"), "w") as f:
            f.write("ddtSchemes\n{\n    default Euler;\n}\n")
        with open(os.path.join(tmp, "system", "fvSolution"), "w") as f:
            f.write("PIMPLE\n{\n    nOuterCorrectors 1;\n}\n")

        activity = read_case_activity(tmp)
        check("temporary case has fvoptions_active=True", activity.fvoptions_active)

        raised = False
        try:
            arm3_library(g, equation="UEqn", case_dir=tmp)
        except ValueError:
            raised = True
        check("arm3_library raises when fvOptions is active", raised)


def check_extra_family_hook() -> None:
    def dummy_extra(Z, basis_ctx):
        return (2.0 * Z[0:1, :])

    register_extra_family("__test_dummy_extra__", dummy_extra)
    library = Library(families=("const", "lin"), extras=("__test_dummy_extra__",))
    Z = pt.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], dtype=pt.float64)
    D, groups = build_regressors(Z, library)
    check("extra family hook: column count", D.shape[0] == 1 + 2 + 1, f"D.shape={tuple(D.shape)}")
    check("extra family hook: group present", "__test_dummy_extra__" in groups)
    check("extra family hook: values correct",
          pt.allclose(D[groups["__test_dummy_extra__"][0], :], 2.0 * Z[0, :]))


def check_dmd_lambda_zero_equivalence() -> None:
    """Synthetic exact-linear-operator recovery: a {lin}-only, lambda=0 fit
    on the raw (uncentred) POD basis must reproduce the forward trajectory
    of a known linear map, the same property flowTorch's exact DMD relies
    on (see run_step4a.py's sanity check for the real-data comparison
    against flowTorch's own DMD implementation)."""
    A = pt.tensor([[0.99, 0.20], [-0.20, 0.99]], dtype=pt.float64)   # a rotation-like stable map
    x = pt.tensor([1.0, 0.0], dtype=pt.float64)
    traj = [x]
    for _ in range(40):
        x = A @ x
        traj.append(x)
    X = pt.stack(traj, dim=1)

    basis = pod_basis(X, r=2, center=False)
    Z = project(basis, X)
    library = Library(families=("lin",), extras=())
    D, groups = build_regressors(Z[:, :-1], library)
    coef = fit_ridge(D, Z[:, 1:], 0.0, 0.0, groups)

    traj_pred, diverged, _ = rollout(coef, Z[:, 0], n_steps=X.shape[1] - 1, kind="discrete", library=library)
    X_pred = basis.modes @ traj_pred
    err = (pt.linalg.norm(X_pred - X) / pt.linalg.norm(X)).item()
    check("lambda=0 DMD-equivalence: not diverged", not diverged)
    check("lambda=0 DMD-equivalence: exact linear recovery", err < 1e-8, f"err={err:.2e}")


def _build_pimplefoam_drag_graph():
    return build_operator_graph(
        UEQN_DRAG, fvschemes_path=FVSCHEMES_DRAG, extra_sources=[PEQN_DRAG],
        include_unqualified=True, expand_dispatch=True,
        turbulence_properties_path=TURB_PROPS_DRAG,
    )


def check_arm3_library_drag_fixture_has_quadratic_drag_extra() -> None:
    """Step 4b: arm3_library on the drag fixture's UEqn (the parsed
    fvm::Sp(cD*mag(U), U) term, labeled implicit_source_nonlinear_drag by
    the operand-aware ontology rule) must add "quadratic_drag" to
    library.extras, with a provenance row recording where it came from --
    not silently drop it, and not raise (it's a mapped, reviewed rule, not
    a needs_review term)."""
    g = _build_pimplefoam_drag_graph()
    lib3 = arm3_library(g, equation="UEqn", case_dir=DATASET_CASE)
    check("arm3_library(drag fixture): quadratic_drag in extras",
          "quadratic_drag" in lib3.extras, f"extras={lib3.extras}")
    check("arm3_library(drag fixture): families unchanged from the baseline arm3/arm2 span",
          lib3.families == arm2_library().families, f"families={lib3.families}")

    drag_rows = [row for row in lib3.provenance if row.get("extra") == "quadratic_drag"]
    check("arm3_library(drag fixture): provenance has exactly one quadratic_drag row",
          len(drag_rows) == 1, f"{len(drag_rows)} rows: {drag_rows}")
    if drag_rows:
        row = drag_rows[0]
        check("arm3_library(drag fixture): quadratic_drag provenance physical_type",
              row["physical_type"] == "implicit_source_nonlinear_drag", f"row={row}")
        check("arm3_library(drag fixture): quadratic_drag provenance qualified_name is fvm::Sp",
              row["qualified_name"] == "fvm::Sp", f"row={row}")

    # And the baseline (unmodified) fixture must NOT pick up the extra --
    # confirms the rule is genuinely operand-aware, not a blanket fvm::Sp
    # rule that would also fire on a (nonexistent, here) linear fvm::Sp.
    g_baseline = _build_pimplefoam_graph()
    lib3_baseline = arm3_library(g_baseline, equation="UEqn", case_dir=DATASET_CASE)
    check("arm3_library(baseline fixture): no quadratic_drag extra",
          lib3_baseline.extras == (), f"extras={lib3_baseline.extras}")


def check_quadratic_drag_columns_match_naive_loop() -> None:
    """The vectorized quadratic_drag EXTRA_FAMILY_REGISTRY callable
    (opinf._quadratic_drag_columns, reached only via the registry here --
    this test doesn't import it directly, to exercise the same lookup
    path build_regressors uses) must match a naive per-cell, per-sample
    Python loop computing Phi^T(|Utilde| Utilde) one column/one cell at a
    time."""
    n_cells, r, n_samples = 5, 3, 4
    modes = pt.linalg.qr(pt.tensor([
        [1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0], [1.0, 1.0, 0.0],
        [0.0, 1.0, 1.0], [1.0, 0.0, 1.0], [1.0, 1.0, 1.0], [0.5, 0.2, 0.1],
        [0.1, 0.5, 0.2], [0.2, 0.1, 0.5],
    ], dtype=pt.float64)).Q[:, :r]   # (2*n_cells, r), orthonormal
    mean = pt.tensor([0.1, -0.05, 0.2, 0.0, 0.15, -0.1, 0.05, 0.0, -0.2, 0.1], dtype=pt.float64)
    from static_rom.opinf import PODBasis
    basis = PODBasis(modes=modes, mean=mean, s=pt.ones(r, dtype=pt.float64))
    basis_ctx = make_basis_ctx(basis, n_cells)

    Z = pt.tensor([
        [0.3, -0.2, 0.5, 0.1],
        [-0.1, 0.4, -0.3, 0.2],
        [0.2, 0.1, -0.4, -0.5],
    ], dtype=pt.float64)

    library = Library(families=("const",), extras=("quadratic_drag",))
    D, groups = build_regressors(Z, library, basis_ctx=basis_ctx)
    got = D[groups["quadratic_drag"], :]

    X = reconstruct(basis, Z)   # (2*n_cells, n_samples)
    naive = pt.zeros((r, n_samples), dtype=pt.float64)
    for s in range(n_samples):
        drag_full = pt.zeros(2 * n_cells, dtype=pt.float64)
        for c in range(n_cells):
            ux, uy = X[c, s].item(), X[n_cells + c, s].item()
            mag = math.sqrt(ux * ux + uy * uy)
            drag_full[c] = mag * ux
            drag_full[n_cells + c] = mag * uy
        for k in range(r):
            naive[k, s] = sum(modes[i, k].item() * drag_full[i].item() for i in range(2 * n_cells))

    err = (got - naive).abs().max().item()
    check("quadratic_drag columns match naive per-cell loop", err < 1e-10, f"max|diff|={err:.2e}")


def check_drag_synthetic_injection() -> None:
    """Full-space synthetic system on n_cells cells with a TRUE
    -cD|u|u drag term (plus a stable linear part and a pointwise-quadratic
    "convection-like" nonlinearity that IS exactly representable by the
    quad family after Galerkin projection, so this isolates the drag term
    as the only genuinely out-of-span piece): simulate, POD it, fit Arm 2
    (const/lin/quad only) and Arm 3 (+ quadratic_drag) with the SAME
    select_lambda, and check Arm 3's validation residual is lower by a
    clear factor and it recovers the drag coefficient approximately."""
    n_cells = 4
    dim = 2 * n_cells
    dt = 0.02
    n_steps = 600
    cD_true = 0.5
    alpha = 0.03

    # Oscillatory-decay linear part (2x2 rotation-decay blocks, distinct
    # frequencies) so the trajectory stays quasi-periodic/multi-modal
    # instead of collapsing onto one dominant direction -- deterministic,
    # no RNG, chosen empirically to give a well-conditioned POD spectrum.
    omegas = (3.0, 5.0, 7.0, 11.0)
    eps = 0.05
    L = pt.zeros((dim, dim), dtype=pt.float64)
    for k, om in enumerate(omegas):
        i, j = 2 * k, 2 * k + 1
        L[i, i] = -eps
        L[j, j] = -eps
        L[i, j] = -om
        L[j, i] = om

    def step(u: pt.Tensor) -> pt.Tensor:
        ux, uy = u[:n_cells], u[n_cells:]
        quad = pt.cat([alpha * (ux * ux - uy * uy), alpha * (2 * ux * uy)])
        mag = pt.sqrt(ux * ux + uy * uy)
        drag = cD_true * pt.cat([mag * ux, mag * uy])
        return u + dt * (L @ u + quad - drag)

    u0 = pt.tensor([0.6, -0.4, 0.5, -0.3, 0.5, 0.3, -0.4, 0.2], dtype=pt.float64)
    traj = [u0]
    u = u0
    for _ in range(n_steps):
        u = step(u)
        traj.append(u)
    X = pt.stack(traj, dim=1)

    r = 4   # partial truncation (dim=8): leaves the drag term genuinely
            # out-of-span for the quad family, not exactly fittable.
    basis = pod_basis(X, r=r, center=True)
    Z = project(basis, X)
    basis_ctx = make_basis_ctx(basis, n_cells)

    lib2 = Library(families=("const", "lin", "quad"), extras=())
    lib3 = Library(families=("const", "lin", "quad"), extras=("quadratic_drag",))

    Z_input, Y, _time_index, _trunc = build_target(Z, "discrete")
    n = Z_input.shape[1]
    n_val = int(round(0.2 * n))
    n_train = n - n_val

    def _fit_and_score(library: Library):
        D, groups = build_regressors(Z_input, library, basis_ctx=basis_ctx)
        D_train, Y_train = D[:, :n_train], Y[:, :n_train]
        D_val, Y_val = D[:, n_train:], Y[:, n_train:]
        lam_lin, lam_quad, _ = select_lambda(Z, library, "discrete", dt=dt, basis_ctx=basis_ctx)
        coef = fit_ridge(D_train, Y_train, lam_lin, lam_quad, groups)
        val_residual = (pt.linalg.norm(coef @ D_val - Y_val) / pt.linalg.norm(Y_val)).item()
        return coef, groups, val_residual

    coef2, _groups2, val2 = _fit_and_score(lib2)
    coef3, groups3, val3 = _fit_and_score(lib3)

    check("drag injection: Arm3 beats Arm2 by >3x on validation residual",
          val2 > 3.0 * val3, f"val2={val2:.3e} val3={val3:.3e} ratio={val2 / val3:.2f}")

    # Recovered drag coefficient: the fitted extra block (r x r) should be
    # approximately -dt*cD_true * I (each POD mode's drag contribution is
    # dominated by its own reconstructed-field component at this
    # truncation) -- read cD off its diagonal.
    extra_block = coef3[:, groups3["quadratic_drag"]]
    cD_est = -(extra_block.diagonal().mean().item()) / dt
    rel_err = abs(cD_est - cD_true) / cD_true
    check("drag injection: Arm3 recovers cD approximately (<=30% relative error)",
          rel_err <= 0.30, f"cD_est={cD_est:.4f} cD_true={cD_true} rel_err={rel_err:.2%}")


def main() -> None:
    check_quadratic_discrete_recovery()
    check_quadratic_continuous_recovery()
    check_linear_map_recovery()
    check_arm2_families()
    check_arm3_matches_arm2_on_dataset_case()
    check_arm3_raises_on_needs_review()
    check_arm3_raises_on_active_fvoptions()
    check_extra_family_hook()
    check_dmd_lambda_zero_equivalence()
    check_arm3_library_drag_fixture_has_quadratic_drag_extra()
    check_quadratic_drag_columns_match_naive_loop()
    check_drag_synthetic_injection()
    print("\nAll static_rom/test_static_rom.py checks passed.")


if __name__ == "__main__":
    main()
